### ISSUE TITLE
Tło w aktywnościach.

### ISSUE THREAD

**Issue by KamilBest** [IgorJaslowski/SmartHome#12]
Zamiast ustawionego tła jako obrazek, to stosujemy coś takiego, pozwala to tworzyć różnokolorowe tła.
Zastosuj to u nas. W android:top="250dp" ustawiasz ile ma zająć gradient, a ile kolor.

I potem w layoucie ustawiasz odnośnik do tego pliku XML z drawable.

`<?xml version="1.0" encoding="utf-8"?>
<layer-list
    xmlns:android="http://schemas.android.com/apk/res/android"
    >
    <item>
        <shape
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:shape="rectangle"
            >
            <corners
                android:radius="3dp"
                />
            <gradient
                android:angle="270"
                android:startColor="@color/colorPrimary"
                android:endColor="@color/colorPrimaryDark"
                android:type="linear"
                />
        </shape>
    </item>
    <item
        android:top="250dp"
        >
        <shape
            android:shape="rectangle"
            >
            <solid
                android:color="#fff"
                />
        </shape>
    </item>
</layer-list>`

**Comment by IgorJaslowski** [comment]
Poprawione w temperature i sensor activity.
