### ISSUE TITLE
Powiadomienia

### ISSUE THREAD

**Issue by KamilBest** [IgorJaslowski/SmartHome#21]
1. Powiadomienia ładują się w złym miejscu. Powinny ładować się w momencie kliknięcia w zakładkę Powiadomienia. Obecnie ładują się tylko przy starcie aplikacji.
Aby zobaczyć nowe trzeba zrestartować apkę.
2. Powiadomienia powinny być posortowane według daty (najnowsze na samej górze).
3. Poprawić format daty
4. Dodać do obiektu powiadomienia: **typ powiadomienia**, według którego będzie ustalał się kolor paska z lewej strony (zielony-git, czerwony - źle) i ewentualnie ikona.

**Comment by IgorJaslowski** [comment]
Poprawione.
