### ISSUE TITLE
Widoki w wypadku braku połączenia z internetem/requestem

### ISSUE THREAD

**Issue by KamilBest** [IgorJaslowski/SmartHome#23]
1.  Przygotować uniwersalny widok, który będzie odpalał się w przypadku braku połączenia z internetem.

Np.
![image](https://user-images.githubusercontent.com/5641133/51988549-317d2680-24a5-11e9-8ef6-9ab0d840b20a.png)

Widok powinien być zrobiony jeden. Domyślnie ukryty, w przypadku błędu (Retrofit - on response failed) ukryć poprzedni i pokazać błąd
np. res/layouts/part_disconnected_error.xml
I powinien być includowany w widokach, gdzie taki błąd się może wydarzyć.

Includujesz za pomocą: w xmlu tych widoków
` <include  android:id="@+id/ID_ELEMENTU"  layout="@layout/part_subtitle" />`

Aby się potem odwołać do elementu z includowanego widoku musisz tak:
1.     @BindView(R.id.ID_ELEMENTU)
    View view;

2. Gdzieś pod oncreate dodać klasę 
static class IncludedLayout {
        @BindView(R.id.search_button)
        Button searchButton;
//tu bindujesz elementy z includowanego
    }

3. w onCreate zbindować element
ButterKnife.bind(this);

        IncludedLayout includedLayout = new IncludedLayout();
        ButterKnife.bind(includedLayout, searchBarLay);

4.

**Comment by IgorJaslowski** [comment]
Poprawione.
